//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTestScenario) DeepCopyInto(out *IntegrationTestScenario) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTestScenario.
func (in *IntegrationTestScenario) DeepCopy() *IntegrationTestScenario {
	if in == nil {
		return nil
	}
	out := new(IntegrationTestScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationTestScenario) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTestScenarioList) DeepCopyInto(out *IntegrationTestScenarioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntegrationTestScenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTestScenarioList.
func (in *IntegrationTestScenarioList) DeepCopy() *IntegrationTestScenarioList {
	if in == nil {
		return nil
	}
	out := new(IntegrationTestScenarioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationTestScenarioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTestScenarioSelector) DeepCopyInto(out *IntegrationTestScenarioSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTestScenarioSelector.
func (in *IntegrationTestScenarioSelector) DeepCopy() *IntegrationTestScenarioSelector {
	if in == nil {
		return nil
	}
	out := new(IntegrationTestScenarioSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTestScenarioSpec) DeepCopyInto(out *IntegrationTestScenarioSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.ResolverRef.DeepCopyInto(&out.ResolverRef)
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]PipelineParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contexts != nil {
		in, out := &in.Contexts, &out.Contexts
		*out = make([]TestContext, len(*in))
		copy(*out, *in)
	}
	if in.Dependents != nil {
		in, out := &in.Dependents, &out.Dependents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTestScenarioSpec.
func (in *IntegrationTestScenarioSpec) DeepCopy() *IntegrationTestScenarioSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationTestScenarioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationTestScenarioStatus) DeepCopyInto(out *IntegrationTestScenarioStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationTestScenarioStatus.
func (in *IntegrationTestScenarioStatus) DeepCopy() *IntegrationTestScenarioStatus {
	if in == nil {
		return nil
	}
	out := new(IntegrationTestScenarioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineParameter) DeepCopyInto(out *PipelineParameter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineParameter.
func (in *PipelineParameter) DeepCopy() *PipelineParameter {
	if in == nil {
		return nil
	}
	out := new(PipelineParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverParameter) DeepCopyInto(out *ResolverParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverParameter.
func (in *ResolverParameter) DeepCopy() *ResolverParameter {
	if in == nil {
		return nil
	}
	out := new(ResolverParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverRef) DeepCopyInto(out *ResolverRef) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]ResolverParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverRef.
func (in *ResolverRef) DeepCopy() *ResolverRef {
	if in == nil {
		return nil
	}
	out := new(ResolverRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestContext) DeepCopyInto(out *TestContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestContext.
func (in *TestContext) DeepCopy() *TestContext {
	if in == nil {
		return nil
	}
	out := new(TestContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubject) DeepCopyInto(out *TestSubject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubject.
func (in *TestSubject) DeepCopy() *TestSubject {
	if in == nil {
		return nil
	}
	out := new(TestSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestSubject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectComponent) DeepCopyInto(out *TestSubjectComponent) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectComponent.
func (in *TestSubjectComponent) DeepCopy() *TestSubjectComponent {
	if in == nil {
		return nil
	}
	out := new(TestSubjectComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectComponentSource) DeepCopyInto(out *TestSubjectComponentSource) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(TestSubjectGitSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectComponentSource.
func (in *TestSubjectComponentSource) DeepCopy() *TestSubjectComponentSource {
	if in == nil {
		return nil
	}
	out := new(TestSubjectComponentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectConstructor) DeepCopyInto(out *TestSubjectConstructor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectConstructor.
func (in *TestSubjectConstructor) DeepCopy() *TestSubjectConstructor {
	if in == nil {
		return nil
	}
	out := new(TestSubjectConstructor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestSubjectConstructor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectConstructorList) DeepCopyInto(out *TestSubjectConstructorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestSubjectConstructor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectConstructorList.
func (in *TestSubjectConstructorList) DeepCopy() *TestSubjectConstructorList {
	if in == nil {
		return nil
	}
	out := new(TestSubjectConstructorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestSubjectConstructorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectConstructorSpec) DeepCopyInto(out *TestSubjectConstructorSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	out.Extractor = in.Extractor
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectConstructorSpec.
func (in *TestSubjectConstructorSpec) DeepCopy() *TestSubjectConstructorSpec {
	if in == nil {
		return nil
	}
	out := new(TestSubjectConstructorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectConstructorStatus) DeepCopyInto(out *TestSubjectConstructorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastProcessedResource != nil {
		in, out := &in.LastProcessedResource, &out.LastProcessedResource
		*out = new(TestSubjectProcessedResource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectConstructorStatus.
func (in *TestSubjectConstructorStatus) DeepCopy() *TestSubjectConstructorStatus {
	if in == nil {
		return nil
	}
	out := new(TestSubjectConstructorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectExtractor) DeepCopyInto(out *TestSubjectExtractor) {
	*out = *in
	out.Source = in.Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectExtractor.
func (in *TestSubjectExtractor) DeepCopy() *TestSubjectExtractor {
	if in == nil {
		return nil
	}
	out := new(TestSubjectExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectFieldSelector) DeepCopyInto(out *TestSubjectFieldSelector) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectFieldSelector.
func (in *TestSubjectFieldSelector) DeepCopy() *TestSubjectFieldSelector {
	if in == nil {
		return nil
	}
	out := new(TestSubjectFieldSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectGitSource) DeepCopyInto(out *TestSubjectGitSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectGitSource.
func (in *TestSubjectGitSource) DeepCopy() *TestSubjectGitSource {
	if in == nil {
		return nil
	}
	out := new(TestSubjectGitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectGitSourceExtractor) DeepCopyInto(out *TestSubjectGitSourceExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectGitSourceExtractor.
func (in *TestSubjectGitSourceExtractor) DeepCopy() *TestSubjectGitSourceExtractor {
	if in == nil {
		return nil
	}
	out := new(TestSubjectGitSourceExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectLabelSelector) DeepCopyInto(out *TestSubjectLabelSelector) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectLabelSelector.
func (in *TestSubjectLabelSelector) DeepCopy() *TestSubjectLabelSelector {
	if in == nil {
		return nil
	}
	out := new(TestSubjectLabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectList) DeepCopyInto(out *TestSubjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestSubject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectList.
func (in *TestSubjectList) DeepCopy() *TestSubjectList {
	if in == nil {
		return nil
	}
	out := new(TestSubjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestSubjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectProcessedResource) DeepCopyInto(out *TestSubjectProcessedResource) {
	*out = *in
	if in.ProcessedAt != nil {
		in, out := &in.ProcessedAt, &out.ProcessedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectProcessedResource.
func (in *TestSubjectProcessedResource) DeepCopy() *TestSubjectProcessedResource {
	if in == nil {
		return nil
	}
	out := new(TestSubjectProcessedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectSelector) DeepCopyInto(out *TestSubjectSelector) {
	*out = *in
	in.Fields.DeepCopyInto(&out.Fields)
	in.Labels.DeepCopyInto(&out.Labels)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectSelector.
func (in *TestSubjectSelector) DeepCopy() *TestSubjectSelector {
	if in == nil {
		return nil
	}
	out := new(TestSubjectSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectSource) DeepCopyInto(out *TestSubjectSource) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(TestSubjectGitSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectSource.
func (in *TestSubjectSource) DeepCopy() *TestSubjectSource {
	if in == nil {
		return nil
	}
	out := new(TestSubjectSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectSourceExtractor) DeepCopyInto(out *TestSubjectSourceExtractor) {
	*out = *in
	out.Git = in.Git
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectSourceExtractor.
func (in *TestSubjectSourceExtractor) DeepCopy() *TestSubjectSourceExtractor {
	if in == nil {
		return nil
	}
	out := new(TestSubjectSourceExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectSpec) DeepCopyInto(out *TestSubjectSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]TestSubjectComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectSpec.
func (in *TestSubjectSpec) DeepCopy() *TestSubjectSpec {
	if in == nil {
		return nil
	}
	out := new(TestSubjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectStatus) DeepCopyInto(out *TestSubjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TestResults != nil {
		in, out := &in.TestResults, &out.TestResults
		*out = make([]TestSubjectTestResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectStatus.
func (in *TestSubjectStatus) DeepCopy() *TestSubjectStatus {
	if in == nil {
		return nil
	}
	out := new(TestSubjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectTemplate) DeepCopyInto(out *TestSubjectTemplate) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectTemplate.
func (in *TestSubjectTemplate) DeepCopy() *TestSubjectTemplate {
	if in == nil {
		return nil
	}
	out := new(TestSubjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSubjectTestResult) DeepCopyInto(out *TestSubjectTestResult) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSubjectTestResult.
func (in *TestSubjectTestResult) DeepCopy() *TestSubjectTestResult {
	if in == nil {
		return nil
	}
	out := new(TestSubjectTestResult)
	in.DeepCopyInto(out)
	return out
}
